# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datastore.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='datastore.proto',
  package='decode.iot.datastore',
  syntax='proto3',
  serialized_options=_b('Z\tdatastore'),
  serialized_pb=_b('\n\x0f\x64\x61tastore.proto\x12\x14\x64\x65\x63ode.iot.datastore\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n\x0cWriteRequest\x12\x14\n\x0c\x63ommunity_id\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x14\n\x0c\x64\x65vice_token\x18\x03 \x01(\tJ\x04\x08\x01\x10\x02J\x04\x08\x04\x10\x05R\npublic_keyR\tpolicy_id\"\x0f\n\rWriteResponse\"\xcc\x01\n\x0bReadRequest\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bpage_cursor\x18\x04 \x01(\t\x12\x11\n\tpage_size\x18\x05 \x01(\r\x12\x14\n\x0c\x63ommunity_id\x18\x07 \x01(\tJ\x04\x08\x01\x10\x02J\x04\x08\x06\x10\x07R\npublic_keyR\tpolicy_id\"N\n\x0e\x45ncryptedEvent\x12.\n\nevent_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xaa\x01\n\x0cReadResponse\x12\x34\n\x06\x65vents\x18\x02 \x03(\x0b\x32$.decode.iot.datastore.EncryptedEvent\x12\x18\n\x10next_page_cursor\x18\x03 \x01(\t\x12\x11\n\tpage_size\x18\x04 \x01(\r\x12\x14\n\x0c\x63ommunity_id\x18\x06 \x01(\tJ\x04\x08\x01\x10\x02J\x04\x08\x05\x10\x06R\npublic_keyR\tpolicy_id2\xb4\x01\n\tDatastore\x12T\n\tWriteData\x12\".decode.iot.datastore.WriteRequest\x1a#.decode.iot.datastore.WriteResponse\x12Q\n\x08ReadData\x12!.decode.iot.datastore.ReadRequest\x1a\".decode.iot.datastore.ReadResponseB\x0bZ\tdatastoreb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_WRITEREQUEST = _descriptor.Descriptor(
  name='WriteRequest',
  full_name='decode.iot.datastore.WriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='community_id', full_name='decode.iot.datastore.WriteRequest.community_id', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='decode.iot.datastore.WriteRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_token', full_name='decode.iot.datastore.WriteRequest.device_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=181,
)


_WRITERESPONSE = _descriptor.Descriptor(
  name='WriteResponse',
  full_name='decode.iot.datastore.WriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=198,
)


_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='decode.iot.datastore.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='decode.iot.datastore.ReadRequest.start_time', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='decode.iot.datastore.ReadRequest.end_time', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_cursor', full_name='decode.iot.datastore.ReadRequest.page_cursor', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='decode.iot.datastore.ReadRequest.page_size', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='community_id', full_name='decode.iot.datastore.ReadRequest.community_id', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=405,
)


_ENCRYPTEDEVENT = _descriptor.Descriptor(
  name='EncryptedEvent',
  full_name='decode.iot.datastore.EncryptedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_time', full_name='decode.iot.datastore.EncryptedEvent.event_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='decode.iot.datastore.EncryptedEvent.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=485,
)


_READRESPONSE = _descriptor.Descriptor(
  name='ReadResponse',
  full_name='decode.iot.datastore.ReadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='decode.iot.datastore.ReadResponse.events', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_page_cursor', full_name='decode.iot.datastore.ReadResponse.next_page_cursor', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='decode.iot.datastore.ReadResponse.page_size', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='community_id', full_name='decode.iot.datastore.ReadResponse.community_id', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=658,
)

_READREQUEST.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_READREQUEST.fields_by_name['end_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ENCRYPTEDEVENT.fields_by_name['event_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_READRESPONSE.fields_by_name['events'].message_type = _ENCRYPTEDEVENT
DESCRIPTOR.message_types_by_name['WriteRequest'] = _WRITEREQUEST
DESCRIPTOR.message_types_by_name['WriteResponse'] = _WRITERESPONSE
DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['EncryptedEvent'] = _ENCRYPTEDEVENT
DESCRIPTOR.message_types_by_name['ReadResponse'] = _READRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), dict(
  DESCRIPTOR = _WRITEREQUEST,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:decode.iot.datastore.WriteRequest)
  ))
_sym_db.RegisterMessage(WriteRequest)

WriteResponse = _reflection.GeneratedProtocolMessageType('WriteResponse', (_message.Message,), dict(
  DESCRIPTOR = _WRITERESPONSE,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:decode.iot.datastore.WriteResponse)
  ))
_sym_db.RegisterMessage(WriteResponse)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), dict(
  DESCRIPTOR = _READREQUEST,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:decode.iot.datastore.ReadRequest)
  ))
_sym_db.RegisterMessage(ReadRequest)

EncryptedEvent = _reflection.GeneratedProtocolMessageType('EncryptedEvent', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTEDEVENT,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:decode.iot.datastore.EncryptedEvent)
  ))
_sym_db.RegisterMessage(EncryptedEvent)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), dict(
  DESCRIPTOR = _READRESPONSE,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:decode.iot.datastore.ReadResponse)
  ))
_sym_db.RegisterMessage(ReadResponse)


DESCRIPTOR._options = None

_DATASTORE = _descriptor.ServiceDescriptor(
  name='Datastore',
  full_name='decode.iot.datastore.Datastore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=661,
  serialized_end=841,
  methods=[
  _descriptor.MethodDescriptor(
    name='WriteData',
    full_name='decode.iot.datastore.Datastore.WriteData',
    index=0,
    containing_service=None,
    input_type=_WRITEREQUEST,
    output_type=_WRITERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadData',
    full_name='decode.iot.datastore.Datastore.ReadData',
    index=1,
    containing_service=None,
    input_type=_READREQUEST,
    output_type=_READRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASTORE)

DESCRIPTOR.services_by_name['Datastore'] = _DATASTORE

# @@protoc_insertion_point(module_scope)
